### ISSUE TITLE
how to deploy

### ISSUE THREAD

**Issue by hadifarnoud** [pierrre/imageserver#11]
we use [Flynn](https://flynn.io/docs/how-to-deploy-go) for our servers. As I'm not an expert when it comes to Go, how can we deploy this app? is there a tutorial?

**Comment by pierrre** [comment]
Hi, thank you for your interest.
This project is a toolkit, not an app. (there is no `main` package)
It means you can build you own app with this toolkit.

That's why there is not tutorial about deployment.
Write your app, then deploy on Flynn with this tutorial https://flynn.io/docs/how-to-deploy-go

I provide several examples here https://github.com/pierrre/imageserver#examples

**Comment by pierrre** [comment]
By the way, you can also write your own components and compose them with this toolkit.

**Comment by hadifarnoud** [comment]
I found your toolkit by searching for imgix alternatives. It would be super cool alternative to imgix.

problem is, I don't know Go.

**Comment by pierrre** [comment]
Go is easy to learn.
http://dave.cheney.net/resources-for-new-go-programmers

I wrote this project as a toolkit instead of an app, because it provides more flexibility for all kinds of usage.
