### ISSUE TITLE
about time.LoadLocation("GMT") in windows server2012 problem

### ISSUE THREAD

**Issue by yimogit** [pierrre/imageserver#21]
in Windows Server 2012 Failure to perform normally `time.LoadLocation("GMT")`

The error is as follows：
```
UTC open C:\Go/lib/time/zoneinfo.zip: The system cannot find the path specified.
```

And I found your questions at go's [issues](https://github.com/golang/go/issues/13581)，But our system is different

I found in the test that the program can be used normally by modifying [imageserver/http/util.go/GMT](https://github.com/pierrre/imageserver/blob/5c91e11ebdb3cdf57276b51a61da886027ed9835/http/util.go#L28) to UTC. Therefore, if the GMT in the source code is changed to UTC, is this correct? I hope to get your suggestion?

```
//src
// var expiresHeaderLocation = getTimeLocation("GMT")
//me code
var expiresHeaderLocation = getTimeLocation("UTC")
```

**Comment by pierrre** [comment]
This will not work.
The `Expires` header requires to use the HTTP date timestamp format, which is RFC1123 with GMT timezone.
You can't use UTC.
See https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html
In practice, GMT and UTC are equal, however the generated string will no be equal, because it will end with `UTC` instead of `GMT.`

**Comment by pierrre** [comment]
You should fix your local Go installation, and provide the required `zoneinfo.zip`.

**Comment by yimogit** [comment]
Thanks
I will [zoneinfo.zip](https://github.com/pierrre/imageserver/files/2166048/zoneinfo.zip)  be uploaded to the server  `C:\Go\lib\time`  successfully solved
