### ISSUE TITLE
Is it possible to load images from a custom folder.

### ISSUE THREAD

**Issue by lishmoshou511** [pierrre/imageserver#8]
Hi, the project is awesome and I like it very much. I want to use it as my image server, however, I found     all the images are loaded from a special folder naming testdata. I am wondering How can I custom some codes to make it possible that I can totally use the project as an image server including getting images from a custom folder on my disk.

**Comment by pierrre** [comment]
Hi, thank you for your interest.
This project is a toolkit: you should not run the examples (https://github.com/pierrre/imageserver/tree/master/examples) for your own usage without modification.

You need to write an implementation of `Server`: https://godoc.org/github.com/pierrre/imageserver#Server
It will read the file from the disk, for the given `source` parameter, extract the format, and return a new `*Image` (https://godoc.org/github.com/pierrre/imageserver#Image).
You should read https://github.com/pierrre/imageserver/blob/master/httpsource/httpsource.go and use it as an example.

I didn't write this implementation, because it won't work if you have multiple servers (you can't access/synchronize the filesystem of another server).
Currently (in production), I store images on Amazon S3, and use `httpsource.Server` to access them.

I think I'll write one, but I can't give you an ETA...

**Comment by lishmoshou511** [comment]
Thanks for your answer. I think I'll study your codes deeply and then do some custom things as you instructed.

**Comment by pierrre** [comment]
it's now available https://godoc.org/github.com/pierrre/imageserver/source/file

**Comment by JandunCN** [comment]
Thanks, I made it.
